import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { WebSocketProvider } from "@/lib/WebSocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 font-sans">
        <ThemeProvider>
          <WebSocketProvider url="ws://localhost:8000/ws">
            {children}
          </WebSocketProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
