services:
    db:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks:
            - my_network

    main:
        build: ./backend
        container_name: main
        environment:
            DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
            JWT_SECRET: your_jwt_secret
            SECRET_KEY: your_secret_key
            ALGORITHM: HS256
        networks:
            - my_network

        depends_on:
            - db
        ports:
            - "8000:8000"

    patient:
        build: ./frontend/patient
        container_name: patient
        networks:
            - my_network
        
        ports:
            - "3000:3000"
        depends_on:
            - main

networks:
    my_network:
        driver: bridge